# Generated by Django 2.2 on 2019-07-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_publication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='page_no',
            field=models.CharField(max_length=20),
        ),
    ]
