# Generated by Django 2.2 on 2019-07-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_publication', '0002_auto_20190702_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='images',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/res/'),
        ),
    ]
