# Generated by Django 2.2 on 2019-07-14 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_publication', '0003_auto_20190714_0851'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publications',
            new_name='Publication',
        ),
    ]
